export const restaurants = [
  {
    id: "1",
    name: "Shah's Halal",
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&h=400&fit=crop",
    cuisine: "Halal / Middle Eastern",
    rating: 4.8,
    reviewCount: 342,
    eta: "15-25 min",
    deliveryFee: 2.49,
    priceRange: "$$",
    featured: true,
    menu: [
      { id: "m1", name: "Chicken over Rice", price: 10.99, description: "Halal chicken with basmati rice, white & hot sauce", category: "Platters", popular: true },
      { id: "m2", name: "Lamb Gyro", price: 9.49, description: "Fresh lamb in warm pita with tzatziki", category: "Wraps", popular: true },
      { id: "m3", name: "Falafel Wrap", price: 8.49, description: "Crispy falafel with hummus and vegetables", category: "Wraps", popular: false },
      { id: "m4", name: "Combo Platter", price: 13.99, description: "Chicken & lamb combo with rice and salad", category: "Platters", popular: true },
      { id: "m5", name: "Baklava", price: 3.99, description: "Flaky pastry with honey and pistachios", category: "Desserts", popular: false },
    ],
  },
  {
    id: "2",
    name: "Thai Canteen",
    image: "https://images.unsplash.com/photo-1562565652-a0d8f0c59eb4?w=600&h=400&fit=crop",
    cuisine: "Thai",
    rating: 4.6,
    reviewCount: 218,
    eta: "20-30 min",
    deliveryFee: 1.99,
    priceRange: "$$",
    featured: true,
    menu: [
      { id: "m6", name: "Pad Thai", price: 12.99, description: "Rice noodles with shrimp, peanuts, and lime", category: "Noodles", popular: true },
      { id: "m7", name: "Green Curry", price: 13.49, description: "Coconut green curry with bamboo shoots", category: "Curries", popular: true },
      { id: "m8", name: "Mango Sticky Rice", price: 6.99, description: "Sweet sticky rice with fresh mango", category: "Desserts", popular: true },
      { id: "m9", name: "Tom Yum Soup", price: 8.99, description: "Spicy and sour soup with shrimp", category: "Soups", popular: false },
    ],
  },
  {
    id: "3",
    name: "Burgers & Brew",
    image: "https://images.unsplash.com/photo-1550547660-d9450f859349?w=600&h=400&fit=crop",
    cuisine: "American / Burgers",
    rating: 4.5,
    reviewCount: 456,
    eta: "15-20 min",
    deliveryFee: 2.99,
    priceRange: "$$",
    featured: false,
    menu: [
      { id: "m10", name: "Classic Smash Burger", price: 11.99, description: "Double smash patty with american cheese", category: "Burgers", popular: true },
      { id: "m11", name: "Truffle Fries", price: 6.49, description: "Crispy fries with truffle oil and parmesan", category: "Sides", popular: true },
      { id: "m12", name: "Milkshake", price: 5.99, description: "Hand-spun vanilla, chocolate, or strawberry", category: "Drinks", popular: false },
    ],
  },
  {
    id: "4",
    name: "Sunrise Sushi",
    image: "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=600&h=400&fit=crop",
    cuisine: "Japanese / Sushi",
    rating: 4.7,
    reviewCount: 189,
    eta: "25-35 min",
    deliveryFee: 3.49,
    priceRange: "$$$",
    featured: true,
    menu: [
      { id: "m13", name: "Spicy Tuna Roll", price: 12.99, description: "Fresh tuna with spicy mayo and cucumber", category: "Rolls", popular: true },
      { id: "m14", name: "Salmon Sashimi", price: 14.99, description: "8 pieces of premium Atlantic salmon", category: "Sashimi", popular: true },
      { id: "m15", name: "Chicken Teriyaki", price: 11.49, description: "Grilled chicken with teriyaki glaze and rice", category: "Entrees", popular: false },
      { id: "m16", name: "Edamame", price: 4.99, description: "Steamed soybeans with sea salt", category: "Appetizers", popular: false },
    ],
  },
  {
    id: "5",
    name: "Taqueria Davis",
    image: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=600&h=400&fit=crop",
    cuisine: "Mexican",
    rating: 4.9,
    reviewCount: 521,
    eta: "10-20 min",
    deliveryFee: 1.49,
    priceRange: "$",
    featured: true,
    menu: [
      { id: "m17", name: "Carne Asada Burrito", price: 9.99, description: "Grilled steak with rice, beans, and salsa", category: "Burritos", popular: true },
      { id: "m18", name: "Street Tacos (3)", price: 7.99, description: "Corn tortillas with cilantro and onion", category: "Tacos", popular: true },
      { id: "m19", name: "Loaded Nachos", price: 8.49, description: "Chips with cheese, beans, guac, and sour cream", category: "Appetizers", popular: true },
      { id: "m20", name: "Horchata", price: 3.49, description: "Traditional rice drink with cinnamon", category: "Drinks", popular: false },
    ],
  },
  {
    id: "6",
    name: "Pho King Good",
    image: "https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?w=600&h=400&fit=crop",
    cuisine: "Vietnamese",
    rating: 4.4,
    reviewCount: 178,
    eta: "20-30 min",
    deliveryFee: 2.49,
    priceRange: "$$",
    featured: false,
    menu: [
      { id: "m21", name: "Pho Bo", price: 11.99, description: "Beef pho with bean sprouts and Thai basil", category: "Soups", popular: true },
      { id: "m22", name: "Banh Mi", price: 8.99, description: "Vietnamese sandwich with pickled veggies", category: "Sandwiches", popular: true },
      { id: "m23", name: "Spring Rolls", price: 5.99, description: "Fresh rice paper rolls with shrimp", category: "Appetizers", popular: false },
    ],
  },
]

export const mockOrders = [
  {
    id: "ORD-001",
    restaurant: "Shah's Halal",
    items: [
      { name: "Chicken over Rice", quantity: 1, price: 10.99 },
      { name: "Lamb Gyro", quantity: 1, price: 9.49 },
    ],
    status: "on_the_way",
    total: 23.47,
    deliveryFee: 2.99,
    date: "2026-02-21T12:30:00",
    eta: "12 min",
    driver: "Jordan R.",
    driverRating: 4.9,
  },
  {
    id: "ORD-002",
    restaurant: "Thai Canteen",
    items: [
      { name: "Pad Thai", quantity: 2, price: 12.99 },
      { name: "Mango Sticky Rice", quantity: 1, price: 6.99 },
    ],
    status: "delivered",
    total: 35.96,
    deliveryFee: 1.99,
    date: "2026-02-20T18:45:00",
    eta: "Delivered",
    driver: "Sam K.",
    driverRating: 4.7,
  },
  {
    id: "ORD-003",
    restaurant: "Taqueria Davis",
    items: [{ name: "Carne Asada Burrito", quantity: 1, price: 9.99 }],
    status: "delivered",
    total: 13.48,
    deliveryFee: 1.49,
    date: "2026-02-19T13:15:00",
    eta: "Delivered",
    driver: "Alex M.",
    driverRating: 5.0,
  },
]

export const availableDeliveries = [
  {
    id: "DEL-001",
    restaurant: "Shah's Halal",
    pickup: "226 E St, Davis",
    dropoff: "Segundo Dining Commons",
    distance: "1.2 mi",
    items: 3,
    estimatedPay: "$6.50",
    timePosted: "2 min ago",
    studentOnly: true,
    biddingTimeLeft: 145,
  },
  {
    id: "DEL-002",
    restaurant: "Taqueria Davis",
    pickup: "505 L St, Davis",
    dropoff: "Shields Library",
    distance: "0.8 mi",
    items: 1,
    estimatedPay: "$4.25",
    timePosted: "5 min ago",
    studentOnly: true,
    biddingTimeLeft: 62,
  },
  {
    id: "DEL-003",
    restaurant: "Burgers & Brew",
    pickup: "403 3rd St, Davis",
    dropoff: "Tercero Residence Halls",
    distance: "1.5 mi",
    items: 4,
    estimatedPay: "$8.75",
    timePosted: "1 min ago",
    studentOnly: false,
    biddingTimeLeft: 180,
  },
]

export const agentStats = {
  todayEarnings: 42.5,
  weeklyEarnings: 285.0,
  totalDeliveries: 156,
  rating: 4.92,
  completionRate: 98,
  activeHours: 3.5,
}

export const restaurantOrders = [
  {
    id: "RO-001",
    customerName: "Alex C.",
    items: [
      { name: "Chicken over Rice", quantity: 2 },
      { name: "Falafel Wrap", quantity: 1 },
    ],
    total: 30.47,
    status: "new",
    time: "2 min ago",
  },
  {
    id: "RO-002",
    customerName: "Sarah M.",
    items: [{ name: "Combo Platter", quantity: 1 }],
    total: 16.98,
    status: "preparing",
    time: "8 min ago",
  },
  {
    id: "RO-003",
    customerName: "Kevin L.",
    items: [
      { name: "Lamb Gyro", quantity: 2 },
      { name: "Baklava", quantity: 2 },
    ],
    total: 25.96,
    status: "ready",
    time: "15 min ago",
  },
  {
    id: "RO-004",
    customerName: "Jamie T.",
    items: [{ name: "Chicken over Rice", quantity: 1 }],
    total: 13.48,
    status: "new",
    time: "1 min ago",
  },
]

export const restaurantMenuItems = [
  { id: "rm1", name: "Chicken over Rice", price: 10.99, category: "Platters", available: true },
  { id: "rm2", name: "Lamb Gyro", price: 9.49, category: "Wraps", available: true },
  { id: "rm3", name: "Falafel Wrap", price: 8.49, category: "Wraps", available: true },
  { id: "rm4", name: "Combo Platter", price: 13.99, category: "Platters", available: true },
  { id: "rm5", name: "Baklava", price: 3.99, category: "Desserts", available: false },
  { id: "rm6", name: "Hummus Plate", price: 6.99, category: "Appetizers", available: true },
]

export const restaurantStats = {
  todayRevenue: 847.5,
  weeklyRevenue: 5230.0,
  totalOrders: 64,
  avgOrderValue: 18.75,
  popularItem: "Chicken over Rice",
  rating: 4.8,
}
